// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {marketdata} from '../models';

export function Emit(arg1:any):Promise<void>;

export function GetAsset(arg1:string):Promise<any>;

export function GetAssets():Promise<Array<any>>;

export function GetCurrentCalendar():Promise<any>;

export function GetIntradayBars(arg1:string):Promise<Array<marketdata.Bar>>;

export function GetLatestTrade(arg1:string):Promise<any>;

export function GetPrevCalendar():Promise<any>;

export function GetSnapshot(arg1:string):Promise<any>;

export function IsReady():Promise<boolean>;

export function Subscribe(arg1:string):Promise<void>;

export function Unsubscribe(arg1:string):Promise<void>;
