// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1) {
  return window['go']['main']['App']['Emit'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetCurrentCalendar() {
  return window['go']['main']['App']['GetCurrentCalendar']();
}

export function GetIntradayBars(arg1) {
  return window['go']['main']['App']['GetIntradayBars'](arg1);
}

export function GetLatestTrade(arg1) {
  return window['go']['main']['App']['GetLatestTrade'](arg1);
}

export function GetPrevCalendar() {
  return window['go']['main']['App']['GetPrevCalendar']();
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}
